### PR TITLE
Corrected name, perhaps a typo

### PR DESCRIPTION
**Pull request by noobshow**

### CODE REVIEW

**Comment by rola93** [comment]
LGTM

**Comment by noobshow** [comment]
@rola93 do you check the diff?

The social handles posted in the second heading wasn't for the name written on it...

**Comment by rola93** [comment]
Of course! just to clarify, Looks Great To Me/Merge

Unfortunately I'm not allowed to merge it, so we need to wait for @OlafenwaMoses

**Comment by noobshow** [comment]
Oww, sorry... I thought you meant nothing wrong("looks good to me").

**Comment by OlafenwaMoses** [comment]
@rola93 Thanks for participating in this discussion.

@noobshow This is good. Thanks for the PR.

@ALL It has been a very hard time for me keeping up with the issues and PRs but I promise things will get better soon, along with new and improved updates to **ImageAI**.

**Comment by noobshow** [comment]
@OlafenwaMoses  You're welcome

**Pull request merged**
