### PR TITLE
#1 get model collection

### PR DESCRIPTION
**Pull request by moethu**
for using tools like lime further down the line one needs to access the loaded models. A getModels method is quite helpful in this case.

### CODE REVIEW

**Comment by moethu** [comment]
I'm using this when using Lime (https://github.com/marcotcr/lime) for example. Lime can generate pictures explaining an image classification visually (https://github.com/marcotcr/lime/blob/master/doc/notebooks/Tutorial%20-%20Image%20Classification%20Keras.ipynb). To make this work in combination with ImageAI one needs to access the loaded models and feed the predict method of a keras model into the Lime explainer:
```
[...]
models = prediction.getModels()
model = models[0]

# Explain using Lime
explainer = lime_image.LimeImageExplainer()
explanation = explainer.explain_instance(images[0], model.predict, top_labels=5, hide_color=0, num_samples=1)
[...]
```

**Comment by moethu** [comment]
sure, sorry - my bad. see commit.

**Comment by OlafenwaMoses** [comment]
I am open to more innovative feature additions like this from you. @moethu

**Comment by moethu** [comment]
Thanks. Great tool by the way, thank you for developing this.

**Comment by OlafenwaMoses** [comment]
I appreciate the compliments @moethu

**Pull request merged**
