### PR TITLE
cleaning MarkDown files

### PR DESCRIPTION
**Pull request by Borda**
refactor all remaining markdown files and keep it clean

### CODE REVIEW

**Comment by Borda** [comment]
@OlafenwaMoses could you have look?

**Comment by Borda** [comment]
is there any interest in using a proper style? @OlafenwaMoses

**Comment by Borda** [comment]
@OlafenwaMoses @OlafenwaMoses  is it a private or community-like repo? so far it looks quite dead...

**Comment by OlafenwaMoses** [comment]
Great work on this. Kind adapt the changes to the new updates.

**Comment by Borda** [comment]
@OlafenwaMoses pls see the update ^^

**Comment by OlafenwaMoses** [comment]
Excellent clean work on the README update. Greatly appreciated.

**Pull request merged**
