### PR TITLE
fix Detection examples

### PR DESCRIPTION
**Pull request by Borda**
* refactor examples code
* fix duplication in Detection class
* fix pkg versions

### CODE REVIEW

**Comment by Borda** [comment]
@OlafenwaMoses @johnolafenwa I have been fixing examples and reduce duplicated code...

**Comment by Borda** [comment]
is there any interest on bug fixing? @OlafenwaMoses

**Comment by Borda** [comment]
@OlafenwaMoses @OlafenwaMoses  is it a private or community-like repo? so far it looks quite dead...

**Comment by OlafenwaMoses** [comment]
> @OlafenwaMoses @OlafenwaMoses is it a private or community-like repo? so far it looks quite dead, no reaction even after multiple reminders... 👎

Hello @Borda , apologies for not attending to all your pull request all this while. I have pretty busy with a number of other project. But I am fully back on the project now.

**Comment by Borda** [comment]
Ok and are willing to make this repo maintainable or what are your goals? (see my final state https://github.com/Borda/ImageAI) because your last changes made several conflicts and if go for resolving them I do not want to waste my time since I have also several other running projects...

**Comment by Borda** [comment]
@OlafenwaMoses ^^

**Comment by OlafenwaMoses** [comment]
Hello @Borda . Thanks very much for your patience. I will provide a contributors guide soon. Pending the time, I will review your previous changes and comment on how they can adapted for the current code base of the project.

**Comment by OlafenwaMoses** [comment]
On #208 , I will really appreciate a good update to the **setup.py**. I am open to ideas as well.

**Comment by OlafenwaMoses** [comment]
On #209, I am open to updates on this again with the current code base.

**Comment by OlafenwaMoses** [comment]
As per #220 , I will love to have the sample codes as simple as possible. This is because a whole lot of users of **ImageAI** are programming newbies. It is of paramount that the example code contains only the class definitions and functions that they need to perform a basic example.

I understand standardization matters, but simplicity is the **number 1** factor intended for this project. Experts can adapt the code with the necessary standards.

**Comment by OlafenwaMoses** [comment]
Also in #220 , I will be grateful for a duplication fix on the [**imageai.Detection.VideoObjectDetection**](https://github.com/OlafenwaMoses/ImageAI/blob/master/imageai/Detection/__init__.py) class, both for the **.detectObjectsFromVideo()** and **.detectCustomObjectsFromVideo()** functions.

The fix desired is to have the video detection functions simply use the image detection to process each frame in the video instead of duplicating the entire model definition and loading process, just as it was implemented in the new [**CustomVideoDetection**](https://github.com/OlafenwaMoses/ImageAI/blob/master/imageai/Detection/Custom/__init__.py) class.

**Comment by OlafenwaMoses** [comment]
If you have any update for #81 for both recognition and detection training , I am game.

**Comment by OlafenwaMoses** [comment]
To make things clearer, I will include pending features in the contributors guide.

**Comment by Borda** [comment]
@OlafenwaMoses could you pls reply to the particular PRs so the communication is clear and straight forward... Thx

**Comment by Borda** [comment]
@OlafenwaMoses And pls drop the comments from this thread which are related to the other PRs... Thx

**Comment by OlafenwaMoses** [comment]
> As per #220 , I will love to have the sample codes as simple as possible. This is because a whole lot of users of **ImageAI** are programming newbies. It is of paramount that the example code contains only the class definitions and functions that they need to perform a basic example.
> 
> I understand standardization matters, but simplicity is the **number 1** factor intended for this project. Experts can adapt the code with the necessary standards.

This applies to this PR

**Comment by Borda** [comment]
Authors are not interested in improvements... :worried:

**Pull request closed without merging**
