### PR TITLE
update setup

### PR DESCRIPTION
**Pull request by Borda**
* remove temporary files
* extend setup.py
* list required libs
* add git ignore
* rename images/videos folder (name confusion)

### CODE REVIEW

**Comment by Borda** [comment]
@OlafenwaMoses minor refactoring according to standard Python projects...

**Comment by Borda** [comment]
is there any interest in properly defined setup? @OlafenwaMoses

**Comment by Borda** [comment]
@OlafenwaMoses @OlafenwaMoses  is it a private or community-like repo? so far it looks quite dead...

**Comment by OlafenwaMoses** [comment]
I will really appreciate necessary update to the setup.py

**Comment by Borda** [comment]
@OlafenwaMoses pls see the update ^^

**Comment by Borda** [comment]
@OlafenwaMoses conflicts resolved... ^^

**Comment by OlafenwaMoses** [comment]
@Borda See the updated comment.

**Comment by Borda** [comment]
@OlafenwaMoses I have added the two packages, but I do not understand why to remove `Keras` since you relied on it... then installation of your package won't work...

**Comment by OlafenwaMoses** [comment]
@Borda Alright. Do include Keras.

**Comment by Borda** [comment]
it is the same story with all other listed packages like `tensorflow`
https://github.com/OlafenwaMoses/ImageAI/blob/master/imageai/Prediction/ResNet/resnet50.py#L1

**Comment by Borda** [comment]
@OlafenwaMoses all conflicts are resolved now...

**Comment by Borda** [comment]
I would reclined other name of "images" folder since it collides with the text "images" which makes any refactoring/rename like operations very difficult... 
Would you have any better name for this folder?
Some other project like scikit-image use "data" folder...

**Comment by OlafenwaMoses** [comment]
Okay. Revert the refactoring operation and change the folder names as below. Ensure only the README are affected:

`data-images`
`data-videos`

**Comment by Borda** [comment]
updated @OlafenwaMoses

**Comment by Borda** [comment]
@OlafenwaMoses I have updated the remaining MarkDown files...

**Comment by Borda** [comment]
@OlafenwaMoses I have updated the remaining MarkDown files...

**Comment by Borda** [comment]
@OlafenwaMoses I believe that now it is ready to merge so we can add basic CI...

**Comment by OlafenwaMoses** [comment]
I need you to review the changes and made amendments. You can see the difference in the active commit to your PR via this link. https://github.com/OlafenwaMoses/ImageAI/pull/208/files

Please make modifications to the following:
- The **TABLE OF CONTENT** menu with missing tag `:white_square_button: ` in some README
- The missing images after the folder rename in the README files
- The change of `images` to `data-images` in critical **.py** files except the ones in the examples folder.

**Comment by Borda** [comment]
@OlafenwaMoses 
> * The **TABLE OF CONTENT** menu with missing tag `:white_square_button: ` in some README

to clarify the `:white_square_button:` maybe will have an effect in the HTML but not here... so would you mind to have the past `&#9635`?

> * The missing images after the folder rename in the README files

I have double-check it now and it should be fine... 1d3acdfe220b74d5e366947f70600fd0c4ca293a

> * The change of `images` to `data-images` in critical **.py** files except the ones in the examples folder.

I have double-check it now and it should be fine... 1d3acdfe220b74d5e366947f70600fd0c4ca293a

**Comment by OlafenwaMoses** [comment]
I will accept this PR and make some changes to the slight modifications to the README. Once I do that, I will let you know. Ensure you consider this update in all your next PRs. 

Also, I will be keeping the requirements.txt for **test** purpose only while the **setup.py** will exclusively specify its requirements. This is to allow users install their desired versions of **Tensorflow** and **Keras**.

**Comment by OlafenwaMoses** [comment]
All slight updates have been done.

**Comment by OlafenwaMoses** [comment]
@Borda . You can a new pull exclusively for the proper **setup.py** update. Dependencies you include the following.

`install_requires=['numpy','scipy','pillow',"matplotlib", "h5py", "keras", "opencv-python"]`

**Comment by Borda** [comment]
I do not agree. for testing is normally folder `tests` and requirements listed there... see for example scikit-image but if you wish so... :smiling_imp:

**Comment by OlafenwaMoses** [comment]
Great then. You can reference the requirements.txt but exclude **Tensorflow** from the dependencies.

**Pull request merged**
