### PR TITLE
refactor README.md

### PR DESCRIPTION
**Pull request by Borda**
one more README.md refactoring @OlafenwaMoses

### CODE REVIEW

**Comment by Borda** [comment]
@OlafenwaMoses conflicts should be resolved now... ^^

**Comment by OlafenwaMoses** [comment]
Hello, I made some changes yesterday to the README to correct the incorrect icons for the **TABLE OF CONTENTS** as well as remove the **download ImageAI wheel** option. Kindly adapt your changes to this new update.

**Comment by Borda** [comment]
@OlafenwaMoses table was already updated and now I have removed the "download ImageAI wheel"

**Comment by OlafenwaMoses** [comment]
Slight changes have been made. Factor the changes into next updates.

**Comment by Borda** [comment]
just done for #208

**Pull request merged**
