### PR TITLE
Bug fix on decode netout

### PR DESCRIPTION
**Pull request by rola93**
- Fix bug described at #338  
- define static methods as static
- refactor the iterations to avoid operations that are not needed (divide, multiply and cast)

### CODE REVIEW

**Comment by rola93** [comment]
I keep reading the code, trying to understand why it still works with such a bug. It turn out that some of those booundingboxes whose objectness is not zero, but are below the required threshold are being kept as proposal. Then, some of them are removed at no maxima supression stage, and at the last step, on `get_boxes operation` there is a last filter step which get rid of those that are below the given threshold.

In addition  to this,  while comparing [current implementation](https://github.com/OlafenwaMoses/ImageAI/blob/8570815e95d3ab62b0129fba94a4255f6540003f/imageai/Detection/Custom/__init__.py#L1239) with [the original](https://github.com/experiencor/keras-yolo3/blob/e1e6073fc49839d027e58487f682de7c8a4184be/utils/utils.py#L169), and I found a small and sutil difference:

ImageAI:
`netout[..., 4:] = self._sigmoid(netout[..., 4:])`
Original:
`netout[..., 4]   = _sigmoid(netout[..., 4])`

I didn't change it on current PR because I can't see how this may change the results. I also have no idea on why are those that different (maybe the _original_ was updated? )

I'll try to track back this file story to see what happen, but I'd appreciate any help @OlafenwaMoses

**Comment by rola93** [comment]
On [this commit](https://github.com/OlafenwaMoses/ImageAI/commit/0c7e4af11f7ad1b4fe2d7011cfb9aa258d6040e2) from @OlafenwaMoses  that is the one which creates the file in ImageAI, the `decode_netout` function is exactly as it was in the original source, so it is clear that the code was changed after the initial commit of the file

**Comment by OlafenwaMoses** [comment]
@rola93 This is really brilliant. Quite a number of unnecessary steps in the code. I missed them due to the avalanche of further tasks that followed the initial release. 

Good to see you got rid of the unnecessary `int` casting operations as well as capturing the boxes below the desired threshold.

The line `netout[..., 4] = _sigmoid(netout[..., 4])`
was changed to `netout[..., 4:] = self._sigmoid(netout[..., 4:])` because the function was called in the same class, the class `CustomDetectionUtils` which holds all post-processing for the detection

I will review this changes further and let you know should any compatible issues arise.

**Comment by rola93** [comment]
Hey! it's a pleasure for me to contribute!

One more question, I don't get the following paragraph:
> The line `netout[..., 4] = _sigmoid(netout[..., 4])`
was changed to `netout[..., 4:] = self._sigmoid(netout[..., 4:])` because the function was called in the same class, the class `CustomDetectionUtils` which holds all post-processing for the detection

Can you explain it once more? maybe there should be a comment on this point in the code, just to prevent someone else from getting stucked/confused at this point in the future

Thanks a lot!

**Comment by OlafenwaMoses** [comment]
The discussion below provides a detailed information on this. 

https://stackoverflow.com/questions/5615648/python-call-function-within-class

**Comment by rola93** [comment]
oh my apologizes. My concern was not tih the difference between  using it as `self.` or not, this is ok.

My point is that there is a small difference which changes a lot the results, that's in the way we're indexing netout:

Current: `netout[..., 4:]`
Original: `netout[..., 4]`

In the original, the selection is taking just one _row_(*), 4, however, the current is taking every single _row_ from 4 to the lastone

(*) are not exactly _rows_ because the selection is done over the last dimention

**Comment by rola93** [comment]
Hey @OlafenwaMoses any news on this? this looks related to #352

**Comment by rola93** [comment]
Well, finally it has nothing to do with #352. The difference is because there are two different implementations of `get_boxes` operation in both, the original and the current implementation.

I didn't fully understand its implications, but my guess is that one of the implementations is for single image predictions and the other for batches of images.

**Pull request merged**
