### PR TITLE
Remove cache files

### PR DESCRIPTION
**Pull request by Borda**
remove temporary and cached files like *.pyc

### CODE REVIEW

**Comment by Borda** [comment]
@OlafenwaMoses I believe that such files should not be part of any repository

**Comment by Borda** [comment]
is there any interest in keeping the project clean? @OlafenwaMoses

**Comment by Borda** [comment]
@OlafenwaMoses @OlafenwaMoses  is it a private or community-like repo? so far it looks quite dead...

**Comment by OlafenwaMoses** [comment]
This has been fixed. Thanks for calling my attention to it.

**Comment by Borda** [comment]
It was not fixed completely...
* there are still cash files in repository
* the git ignore list is not complete

**Comment by OlafenwaMoses** [comment]
Okay then. I will appreciate an update on the .gitignore

**Comment by Borda** [comment]
@OlafenwaMoses pls see the update ^^

**Pull request merged**
