### PR TITLE
Add CI

### PR DESCRIPTION
**Pull request by Borda**
* add Travis config
* add requirements
* add Travis, CodeCov & CodeFactor badges
* refactor README - using true MarkDown
* fix setup params
* fix doctest imports 

[Build Status](https://travis-ci.org/Borda/ImageAI)
[codecov](https://codecov.io/gh/Borda/ImageAI)
[CodeFactor](https://www.codefactor.io/repository/github/borda/imageai/overview/add-CI)

### CODE REVIEW

**Comment by Borda** [comment]
@OlafenwaMoses @johnolafenwa pls create the Travis/CodeCov/CodeFactor under your accounts and update the badges (paths) accordingly...

**Comment by Borda** [comment]
is there any interest on the code sustainability? @OlafenwaMoses

**Comment by Borda** [comment]
@OlafenwaMoses @OlafenwaMoses  is it a private or community-like repo? so far it looks quite dead...

**Comment by OlafenwaMoses** [comment]
On #209, I am open to updates on this again with the current code base as per
- CI
- README cleaning
- code factor badges

**Comment by Borda** [comment]
it is waiting for resolving #208

**Comment by Borda** [comment]
@OlafenwaMoses tests are passing, could you create your accounts at Travis. CodeFactor and Codecov and update badges to refer top your project...

**Comment by Borda** [comment]
it would be nice to follow PEP8, but it is quite a lot of work...
try to run locally `flake8 imageai --max-line-length=120`

**Comment by Borda** [comment]
@OlafenwaMoses ^^

**Comment by Borda** [comment]
@OlafenwaMoses it seems that you started to implement Travis on your own... What don't you like on this PR? Pls, let me know keeping this PR updated takes some and if you do not want it...

**Comment by Borda** [comment]
@OlafenwaMoses it would be much easier when you would accept this PR and start adding a new test with initial test status as passing which I proposed here...

**Comment by Borda** [comment]
@OlafenwaMoses obviously you have an issue since your tests are taking quite some time on normal CPU machine (as Travis) and so it reaches timeout limit, see https://travis-ci.com/Borda/ImageAI/jobs/224712462

**Comment by Borda** [comment]
fixing bug from a69db50b058a0ea85ba8ef4d08a4eb7bd64ef521 432027cc98d13b5915721dacbdc2853910c6710d c035250ef03feb4a0d51b20ad3a987bcb41dd4a5
Alo all required models from https://github.com/OlafenwaMoses/ImageAI/blob/master/test/test_custom_recognition.py are missing so the should be dropped

**Comment by Borda** [comment]
@OlafenwaMoses your last 10 commits toying with Travis looks like wasting your and my time! What is wrong with accepting my already working Travis CI?

**Comment by OlafenwaMoses** [comment]
I am currently developing a full-featured test suite for this project and will be matured in coming days.

You have done a great deal of work on this PR. However, there are way to many changes to commit, some of which will generate errors and lead to compatibility issues.

I will advice that in you keep your PRs as focused as possible to ensure they can be reviewed on time and addressed as appropriate. In short, let PR for the **setup.py**, **testing** , **code changes** and others standalone.

**Comment by Borda** [comment]
You can review my work per commit and your advice is miss leading since without fixes the tests will not pass!
I have added CI but your code was bugy in couple places so I have to fix it...
The PR was simply adding CI at the fist place but you didn't accept it and instead you started to add extra things which made conflicts (then I had to resolve)
I feel very disappointed with your approach.

**Comment by Borda** [comment]
Pls, point out single error produced by my commit compare to the initial state...

**Comment by Borda** [comment]
just wasting time and effort of people who wants to help... :worried:

**Comment by Borda** [comment]
you may do cherry-pick of particular commit although you will rather make it as own commits... :laughing:

**Pull request closed without merging**
