### PR TITLE
Make object detection capable of using in multiple thread

### PR DESCRIPTION
**Pull request by witoong623**
Normally, when `ObjectDetection` is created and load model in other thread and then is used in another thread, Tensorflow will complain that the tensor is not element of this graph.  

This PR uses [Graph.as_default()](https://www.tensorflow.org/api_docs/python/tf/Graph#as_default) to make the current graph to be the default one (the one that is used while load model).  I added flag `thread_safe` for turning on and of this thread safe behavior to both `detectObjectsFromImage` and `detectCustomObjectsFromImage` methods with default value to false.  

**Related API reference**

- [Session.as_default()](https://www.tensorflow.org/api_docs/python/tf/Session?hl=en#as_default)
- [Session.graph property](https://www.tensorflow.org/api_docs/python/tf/Session?hl=en#graph)
- [Graph.as_default()](https://www.tensorflow.org/api_docs/python/tf/Graph#as_default)

P.S. I don't really know about Tensorflow and its API 😅, please correct me if I misunderstand.

### CODE REVIEW

**Comment by OlafenwaMoses** [comment]
This is a very great contribution. I will make thorough review of this in coming days to ensure it is stable. Once I do, I will gladly welcome it into the project, and will be happy to have it integrated to the entire APIs covered in **ImageAI**

**Comment by cfournel** [comment]
will it resolve the issue from the firstvideodetection example ? its seems related to a thread safe issue

**Comment by OlafenwaMoses** [comment]
@witoong623 This is an excellent contribution. I have tested this and it works perfectly. I will further extend it to the other detection and prediction classes.

**Comment by rola93** [comment]
If you are considering to add production deployment capacities to imageAI, it may be a good idea to include Tensoflow serving models and a client for it, since preprocessing/postprocessing are not that trivial

Sounds like a great idea

**Comment by OlafenwaMoses** [comment]
Thanks for the comment @rola93 .  I will take note of this and will consider it for future updates.

**Comment by GusBricker** [comment]
Are you able to provide an example of how this should be used? As I am having trouble getting it to work using Flask across multiple threads.

**Pull request merged**
